### ISSUE TITLE
Create a Google Sheet document with all the measures from countyhealthrankings.org

### ISSUE THREAD

**Issue by kb22** [TheRensselaerIDEA/MortalityMinder#11]
https://docs.google.com/spreadsheets/d/1tmCAfR2Et6_T9eIruQob6iaWwKYSsZ9N/edit?usp=drive_web&ouid=107542215525958288886&dls=true

**Comment by F-said** [comment]
"Cohort" social determinant is not listed in county health rankings data

**Comment by kb22** [comment]
I think that is from another data source which we can look as part of another issue. The work here is completed. It's good to close.
