### ISSUE TITLE
County names in by time period leaflet maps are incorrect

### ISSUE THREAD

**Issue by RossDeVito** [TheRensselaerIDEA/MortalityMinder#125]

**Comment by kb22** [comment]
Can you provide the description of what the bug is?

**Comment by olyerickson** [comment]
It's pretty simple: While the counties that are popping up are in fact NY counties, they are showing up in the wrong places. They are wrong for all three maps --- the cluster map and the two on the right.

**Comment by olyerickson** [comment]
I've flagged this a "Top Priority" because it will be spotted very quickly.

**Comment by olyerickson** [comment]
Other states are wrong; it's not just NY. For example, VT is wrong.

**Comment by kb22** [comment]
Got it. I’ll fix the bug.
