### ISSUE TITLE
Add text to the Landing page. 

### ISSUE THREAD

**Issue by hosam-hamed-33** [TheRensselaerIDEA/MortalityMinder#194]
**This should go in the text box on the left hand side. There should be some type of divider where there is a dashed line in the text below.**

MortalityMinder analyzes trends of premature death in the United States which are caused by:

- Deaths of Despair: Deaths due to suicide, overdose, substance abuse and poisonings.
   Assault Deaths: Deaths due to intentional injuries inflicted by another person.
- Cardiovascular Disease Deaths: Deaths due to diseases of the circulatory systems such    
   as heart disease and stroke.
- Cancer Deaths: Deaths due to cancer and neoplasm. 

The mortality rate used in the app is the number of people per 100,000 that died prematurely in a given county during a three year period.  To represent premature  death, the rate includes all deaths for the selected causes in individuals age 25 to 64. 

---------------------------------------------------------------------------------------

Pick the cause of death on the menu bar to see how mortality rates in the United States have changed from 2000 to 2017. The map shows the changes by county
The graph shows the average mortality rate of the United States.

To help address why rates are changing, MortalityMinder analyzes factors such as social determinants that are associated with increased mortality rates.
 
Click right and left to investigate more.

**Comment by olyerickson** [comment]
Added to the "Nationwide" page. Closing...
