### ISSUE TITLE
Add text to the 1st Tab

### ISSUE THREAD

**Issue by hosam-hamed-33** [TheRensselaerIDEA/MortalityMinder#195]
**Where there is a bold here indicated that there needs to be a hyperlink that goes to another page with more info. At this time those pages have not been established.** 

On the left hand side there is a heading which reads: “Exploring Causes of Premature Death” Next to it there should be a small question mark. When hovering over it the following should be shown in a small popup: The mortality rate used in the app is the number of people per 100,000 that died prematurely in a given county during a three year period. A premature death is considered anyone that dies between the ages of 25 to 64 as a result of the selected cause.

On the right hand side there is a heading which reads: “What are the Social Determinants of Mortality”. A suggestion was made to change this to: “Most Influential Factors”. In any case when hovering over the small question mark that is next to it a popup should be shown that contains the following: Each factor is rated as Destructive, meaning that it has a positive correlation with the death rate; or Protective, meaning it has a negative correlation with the death rate. The application is showing those factors which have the highest absolute correlation with mortality. For more information on the method of determining correlation please navigate **here.** 

On the map which is titled “NY - Death of (Cause) Rate” there should be a small question mark next to the title which when hovered over opens a small popup that says: This map is a visualization of each of the individual counties within the selected state. Lighter colors indicate lower premature deaths, while darker colors are the inverse. The key for each of the specific colors is provided beneath the map of the state. Additionally, the desired time range can be selected via the “Select years:” option beneath the key. 

On the map which is titled “NY Trend Cluster Geo Distribution” there should be a small question mark next to the title which when hovered over opens a small popup that says: This map visualizes the counties within the selected state and divides them into three clusters of counties that have similar rates of premature deaths. The “Low” cluster is the grouping of counties that have relatively lower deaths compared to the rest of the state. The “Medium” cluster is the grouping of counties that have average premature deaths compared to the rest of the state. The “High” cluster is the grouping of counties that have relatively higher deaths compared to the rest of the state. For more information on the method of determining clustering please navigate **here.** 

On the chart which is titled “NY-Death of Despair Trend” there should be a small question mark next to the title which when hovered over opens a small popup that says: This plot represents the average premature deaths for each cluster. For more information on the method of determining clustering please navigate **here.**

**Comment by olyerickson** [comment]
"Info" icons and hover text implemented for upper right and upper left panels of Page 1.

**Comment by olyerickson** [comment]
All help text added for page 1. Closing ticket...but we need to work on more uniform styling!
