### ISSUE TITLE
Work on interactive version of Tim's Lattice (be able to toggle between years) [MM_Core]

### ISSUE THREAD

**Issue by ChristinavanHal** [TheRensselaerIDEA/MortalityMinder#2]
We want an interactive version of the Nationwide GIF Tim made. The problem is that we want people to be able to choose the year and enter the app through that choice on a Nationwide page. I believe using the code from Tim's Lattice would probably be an easier basis, but that goes under your problem.

**Comment by bennek2** [comment]
This is kind of a core issue.   Are we doing D3 to improve interactivity or animations or not?

Kristin
