### ISSUE TITLE
On deep dive page, if your change the death cause it jumps you to the landing page

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#298]
It should keep you on the same page.

**Comment by olyerickson** [comment]
I'm not seeing this... When I change the cause it stays on that same page as expected...

**Comment by olyerickson** [comment]
Okay, I saw this...

**Comment by olyerickson** [comment]
Doesn't do this for e.g. New York. Does do it on California, which is also showing an error.
