### ISSUE TITLE
deepdive wyoming cancer . deaths sometimes show 2 clusters for some factors

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#306]

**Comment by ChristinavanHal** [comment]
Looks like it's an issue with teen birth rate, dentist ratio is having severe issues (similar to the other ones posted), and everything else is working. My guess is that it has to do with the number variables issue mentioned previously and there is probably an issue with the clustering/bar chart categories for teen birth rate.
