### ISSUE TITLE
Could lollipop graph be drawn once and then saved to make more efficient?

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#332]
Right now the lollipop graph is created twice. Couldn't we just keep it in an object and then just call it the second time?  This would make the code more computationally efficient and easier to maintain.

**Comment by olyerickson** [comment]
The performance impact of generating those really isn't significant. Plus we don't want to lose our interactivity. 

We have bigger fish to fry...

**Comment by josefigueroa168** [comment]
To be addressed in the future
