### ISSUE TITLE
Cardiovascular national page -- the 2015-2017 button dispears

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#495]

**Comment by kb22** [comment]
It button appears to be working now, thus closing the issue.

<img width="1439" alt="Screen Shot 2019-12-02 at 1 11 00 AM" src="https://user-images.githubusercontent.com/14316277/69934692-aa238980-14a0-11ea-8b2f-a9b493b3c10b.png">
