### ISSUE TITLE
Add SOMETHING for Determinant geo-plot (Page 3) when United States is selected

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#496]
We need SOMETHING there when United States is selected

**Comment by bennek2** [comment]
Had an idea for this one.  Put in the text in the social determinants csv that describe why the factor matters.   Easy peasy.  It's useful and quick.

**Comment by RossDeVito** [comment]
I've added that text to the usual determinant text section (#574). I think it would be best to pre-generate nationwide map images for each determinant and then display those in the space
