### ISSUE TITLE
Moused-over button disappears on Page 1 when cause other than Despair is selected

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#498]

**Comment by bennek2** [comment]
<img width="611" alt="Screen Shot 2019-11-25 at 8 30 39 PM" src="https://user-images.githubusercontent.com/12432288/69591982-848b1180-0fc2-11ea-8a79-d16e87d1a9b4.png">

**Comment by bennek2** [comment]
the 20150-2017 doesn't show at all and the buttons are supposed to be grey

**Comment by josefigueroa168** [comment]
Will look into this tomorrow
