### ISSUE TITLE
Need  to test every state and every cause and report bugs

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#506]

**Comment by bennek2** [comment]
Make issues for every bug you find.

**Comment by Darkknight6940** [comment]
1. When switch from other state to Alaska with All Cause, the diagram of Socio-Economic and Mortality Relationship for Alaska on the third page can not be shown correctly. But this happens randomly, sometimes it works.
Error :Aesthetics must be either length 1 or the same as the data (1): x, y, group
2. For Hawaii with all four causes , the two diagram of  relationship of social determinants and mortality can not show correctly.
Error:'length.out' must be a non-negative number
3.When switch from other state to Virginia with Death of Despair, the diagram ofDeaths of Despair Trends for Virginia on the second page can not be shown correctly. 
Error:Unknown column `2000-2002`

**Comment by Darkknight6940** [comment]
All states with fewer than 6 states (Hawaii, Rhode Island, Delaware) checked 
All social determinants checked.Only bug found happens in multiple states.
![捕获](https://user-images.githubusercontent.com/42753033/69888655-088f1300-12bb-11ea-9fec-b91beb7624e5.PNG)
![捕获2](https://user-images.githubusercontent.com/42753033/69888656-088f1300-12bb-11ea-822f-d1833f26c045.PNG)Is the data not yet updated?

**Comment by Darkknight6940** [comment]
Test all states and all social determinants again, no bugs
