### ISSUE TITLE
states page messes up a tad on my powerbook.

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#519]
The text in first column overlaps with bottom graph.  I can fix this only if I go into full screen mode.  This suggest to me that the text is too long and should be shorten.
One thought is to remove
this statement from left
xThe right graph shows factors correlated associated with mortality disparities.
and instead expand the text a bit on far right.

**Comment by bennek2** [comment]
<img width="950" alt="Screen Shot 2019-11-25 at 8 05 41 PM" src="https://user-images.githubusercontent.com/12432288/69590933-142ec100-0fbf-11ea-8bd6-51d063b8f1d4.png">

**Comment by kb22** [comment]
Already fixed it as part of another PR for small fixes.
