### ISSUE TITLE
Bug in hawaii when picking  graphs don't appear -- see pictures for details

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#528]
<img width="1389" alt="Screen Shot 2019-11-26 at 2 36 04 PM" src="https://user-images.githubusercontent.com/12432288/69666480-51945c80-105a-11ea-8187-42ca3dda380c.png">

**Comment by kb22** [comment]
This is same as the other bug (https://github.com/TheRensselaerIDEA/MortalityMinder/issues/534) so closing this one.
