### ISSUE TITLE
Alaska has a bug in the dot plot 

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#533]
<img width="1421" alt="Screen Shot 2019-11-26 at 2 53 39 PM" src="https://user-images.githubusercontent.com/12432288/69667769-9caf6f00-105c-11ea-9091-51da95bb9d55.png">

**Comment by bennek2** [comment]
Note this only happens if you switch states first.  If you come back to it by switching determinants it works fine.

**Comment by Random-W** [comment]
I cannot reproduce this error. 
Here is what I did:
1. Change state to Alaska
2. Turn to the dot plot page
![image](https://user-images.githubusercontent.com/33356939/69893211-33d62a00-12dc-11ea-8fdb-10100cc9c850.png)
