### ISSUE TITLE
Factor description crashes for some factors

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#558]
I believe problem is associated with missing values in the social determinants.
<img width="1385" alt="Screen Shot 2019-12-01 at 3 41 02 PM" src="https://user-images.githubusercontent.com/12432288/69920045-4faf0c80-1451-11ea-933c-6d90bc62f46f.png">

**Comment by kb22** [comment]
It appears that the error is in the line
```
kendall.cor()[kendall.cor()$chr_code == input$determinant_choice,]$kendall_p > .05
```
in `app.R`
