### ISSUE TITLE
Format text on left of national page to be as recommended by designers. See photo

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#623]

**Comment by bennek2** [comment]
<img width="679" alt="MortalityMinder Information Box 2" src="https://user-images.githubusercontent.com/12432288/70245904-d6f7cb00-1744-11ea-9cc6-6cb0a8b78165.png">

**Comment by olyerickson** [comment]
I think this can be done by setting a margin for `li` elements in the CSS

**Comment by olyerickson** [comment]
Took care of this during my most recent addition of subtitles and footnotes
