### ISSUE TITLE
Text on page 4 gets bigger on safari

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#635]

**Comment by josefigueroa168** [comment]
Can you tell me what conditions (Assuming macbookpro, but what size was the window etc) happened here. I can't replicate this.

**Comment by bennek2** [comment]
I just open app on safari on my MacBook Pro and go to full screen. Why don't we let it be.  I'm not sure that it is a bad thing that it gets bigger text and scrolls for that page.
