### ISSUE TITLE
Implement ADA Compliance on figures where possible

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#638]
See these suggestions, specific to visualizations:
https://www.sagepath.com/blogs/development/articles/making-images-readable-to-meet-ada-compliance

**Comment by josefigueroa168** [comment]
Added alt tags to images that are not titled. Will leave this open in case other accessibility concerns can be addressed.

**Comment by kb22** [comment]
I'll be taking over this and address all ADA concerns in the application.
