### ISSUE TITLE
ADD NATIONAL MEAN TO THE MORTALITY PLOTS AS A BLACK LINE.  MAKE SURE IT IS LABELED AS SUCH ON THE LEGEND.

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#78]

**Comment by olyerickson** [comment]
We're still waiting for this. @Darkknight6940 how's it going???

**Comment by Darkknight6940** [comment]
> We're still waiting for this. @Darkknight6940 how's it going???

Just can not manually add the legend

**Comment by olyerickson** [comment]
@Darkknight6940  If your nationwide mean code is otherwise working (except for the legend) just do a pull request and we'll figure it out.
