### ISSUE TITLE
Delaware crashes because only three counties. Make it so it plots all three counties and doesnot do clustering.

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#82]
Someone did fix this so I'm closing this issue.

**Comment by olyerickson** [comment]
Adding a screen shot for emphasis 
![image](https://user-images.githubusercontent.com/358649/66337349-f624d880-e90c-11e9-8b77-19d9724c5b26.png)

**Comment by olyerickson** [comment]
It's very difficult to diagnose the exact cause of the Delaware issue, but judging from the log it looks like ggplot didn't find all of the data it was looking for when building the lollipop plot:
```
Warning: Error in : Aesthetics must be either length 1 or the same as the data (1): x, yend, xend, colour, fill
  182: stop
  181: check_aesthetics
  180: f
  179: l$compute_aesthetics
  178: f
  177: by_layer
  176: ggplot_build.ggplot
  174: print.ggplot
  166: func
  164: f
  163: Reduce
  154: do
  153: hybrid_chain
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$page1.bar.cor1
    1: runApp
```

**Comment by olyerickson** [comment]
I suspect this is a worst-case scenario, but the issue with Maine was probably similar (ie a soft fail, whereas this was hard)

**Comment by olyerickson** [comment]
Note that other small states look great, e.g. Wyoming.

**Comment by bennek2** [comment]
It’s probably because there are so few counties so the clustering failed.
For that few we shouldn’t cluster at all.

Kristin
