### ISSUE TITLE
Maine crashes in deaths of despair.

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/MortalityMinder#87]

**Comment by olyerickson** [comment]
I'm adding a screen shot to emphasize the problem with Maine 
![image](https://user-images.githubusercontent.com/358649/66337015-4cdde280-e90c-11e9-9da2-9f793701cea9.png)

**Comment by taraskami** [comment]
Looks resolved to me? Kind of hard for me to see the issue to begin with.

**Comment by olyerickson** [comment]
Closing ticket
